# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-02 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
